name: CI (git)

on:
  push:
    paths:
      - 'git/**'
      - '.github/workflows/ci-git.yaml'
  pull_request:
    paths:
      - 'git/**'
      - '.github/workflows/ci-git.yaml'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: CI
        uses: its-me/action.aur.ci@v0
        with:
          path: git
          github-token: ${{ secrets.GITHUB_TOKEN }}
