name: CI (release)

on:
  push:
    paths:
      - 'release/**'
      - '.github/workflows/ci-release.yaml'
  pull_request:
    paths:
      - 'release/**'
      - '.github/workflows/ci-release.yaml'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Stage package
        run: cp release/PKGBUILD release/.SRCINFO .

      - name: CI
        uses: its-me/action.aur.ci@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
