name: Publish release package to AUR

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: "Commit message (optional)"
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: dummy-package
      url: https://github.com/its-me/dummy.aur.package
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Publish
        uses: its-me/action.aur.publish@v0
        with:
          path: release
          ssh-key: ${{ secrets.DUMMY_PACKAGE_SSH_KEY }}
          strict-host-checking: false
          destination: ssh://git@github.com/its-me/dummy.aur.package.git
          package-name: package
          git-user-name: Sergey Kanafyev
          git-user-email: sergeykanafyev@gmail.com
          commit-message: ${{ github.event.inputs.commit_message }}
