name: Update git package

on:
  schedule:
    - cron: '30 0 * * 0'
  workflow_dispatch:

env:
  PKG_PATH: git

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.update.outputs.updated }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Update
        id: update
        uses: its-me/action.aur.update@v0
        with:
          path: ${{ env.PKG_PATH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: Sergey Kanafyev
          git-user-email: sergeykanafyev@gmail.com

  ci:
    needs: update
    if: needs.update.outputs.updated == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}

      - name: CI
        uses: its-me/action.aur.ci@v0
        with:
          path: ${{ env.PKG_PATH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: [update, ci]
    if: needs.update.outputs.updated == 'true'
    runs-on: ubuntu-latest
    environment:
      name: dummy-package-git
      url: https://github.com/its-me/dummy.aur.package-git
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}

      - name: Publish
        uses: its-me/action.aur.publish@v0
        with:
          path: ${{ env.PKG_PATH }}
          ssh-key: ${{ secrets.DUMMY_PACKAGE_GIT_SSH_KEY }}
          strict-host-checking: false
          destination: ssh://git@github.com/its-me/dummy.aur.package-git.git
          package-name: package-git
          git-user-name: Sergey Kanafyev
          git-user-email: sergeykanafyev@gmail.com
